#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-20"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "466f7eb86b6a489396cdcc9e25044cfd" }
]

[assets]
directory = "./public"
